services:
  searxng:
    image: searxng/searxng
    restart: always

    ports:
      - "${SEARXNG_PORT}:8080"
    environment:
      - BASE_URL=http://0.0.0.0:2946
      - INSTANCE_NAME=the-index
    volumes:
      - ./searxng/:/etc/searxng

  db:
    image: postgres
    platform: linux/arm64/v8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql
      # - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database_data:
    driver: local
